### PR TITLE
Fix right-side bar hrefs in docs

### PR DESCRIPTION
**Pull request by pedroscaff**
The hrefs with `&` still don't work properly, but it is an issue with https://github.com/facebook/docusaurus, I will report it there and post it here.

### CODE REVIEW

**Comment by pedroscaff** [comment]
https://github.com/facebook/docusaurus/issues/1877

**Comment by Nevon** [comment]
Thanks for reporting the issue to docusaurus. I won't merge this PR, however, as we intentionally create our own anchor links. The reason is that we ship references to the documentation as part of KafkaJS' error messages, which means that we need the links to never change, even if we end up changing the title or Docusaurus changes the way they generate anchors.

**Comment by pedroscaff** [comment]
Do you think that is the best way to do it? I think breaking the documentation navigation is not a good solution for the issue. Docusaurus generates the anchors as we would expect (bugs aside hehe), so we could stick to what they generate.

**Comment by Nevon** [comment]
> I think breaking the documentation navigation is not a good solution for the issue.

No, of course, we don't want the sidebar nav to break either. I think facebook/docusaurus#561 is the correct solution.

Maybe a workaround could be to generate the anchor via Docusaurus and _also_ have our own stable anchor. That way the links in error messages keep working, while the sidebar nav also works, even if they link to different anchors.

**Pull request closed without merging**
