### PR TITLE
Add a docker configuration for running with Kafka 2.4.2

### PR DESCRIPTION
**Pull request by ankon**
This is cherry-picked from https://github.com/figma/kafkajs/commit/f1a090999f078fcb16f24a40d589e39aebd112d8,
and then I adjusted for the recent changes in master as well as updated to Confluent Kafka 5.4.2.

### CODE REVIEW

**Comment by ankon** [comment]
Mostly for the record: This also links to #713.

**Comment by ankon** [comment]
Rebased, and added https://github.com/tulios/kafkajs/pull/763/commits/df97b785e3ad00e280fdbdcef67fa31c34f6b754 to fix a problem in the describe configs test.

**Comment by Nevon** [comment]
It seems the errors in the listgroups/deletegroups tests are persistent with this version of Kafka, and not just flakiness. Every run I've seen now has failed due to those tests, so there may be a bug somewhere (either in KafkaJS or the tests)

**Comment by ankon** [comment]
True that:
~~~~
kafka1 [2020-06-25 18:08:07,144] ERROR Exception while processing request from 127.0.0.1:9092-127.0.0.1:51474-126 (kafka.network.Processor)
kafka1 org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: 16
kafka1 Caused by: java.nio.BufferUnderflowException
kafka1 	at java.nio.Buffer.nextGetIndex(Buffer.java:500)
kafka1 	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
kafka1 	at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:144)
kafka1 	at org.apache.kafka.common.protocol.ByteBufferAccessor.readUnsignedVarint(ByteBufferAccessor.java:58)
kafka1 	at org.apache.kafka.common.message.RequestHeaderData.read(RequestHeaderData.java:132)
kafka1 	at org.apache.kafka.common.message.RequestHeaderData.<init>(RequestHeaderData.java:83)
kafka1 	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:93)
kafka1 	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:904)
kafka1 	at kafka.network.Processor.$anonfun$processCompletedReceives$1$adapted(SocketServer.scala:900)
kafka1 	at scala.collection.Iterator.foreach(Iterator.scala:941)
kafka1 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
kafka1 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
kafka1 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
kafka1 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
kafka1 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
kafka1 	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:900)
kafka1 	at kafka.network.Processor.run(SocketServer.scala:790)
kafka1 	at java.lang.Thread.run(Thread.java:748)
~~~~

... let's see :)

**Comment by ankon** [comment]
So, the thing here is that Kafka 2.4.0 supports "[tagged fields (KIP-86)](https://cwiki.apache.org/confluence/display/KAFKA/KIP-482%3A+The+Kafka+Protocol+should+Support+Optional+Tagged+Fields#KIP482:TheKafkaProtocolshouldSupportOptionalTaggedFields-RequestHeaderVersion1)", which introduce a new encoding scheme for unsigned varints, and new messages that contain these.

The listGroups v2 and deleteGroups v3 requests that KafkaJS uses _should_ have a tag buffer field at the end, and similarly the responses need to handle these as well. In principle the writing of these tag buffers isn't hard:
```diff
diff --git a/src/admin/index.js b/src/admin/index.js
index c1d65db..44e4979 100644
--- a/src/admin/index.js
+++ b/src/admin/index.js
@@ -44,6 +44,9 @@ const findTopicPartitions = async (cluster, topic) => {
     .sort()
 }
 
+/**
+ * @returns {import("../..").Admin}
+ */
 module.exports = ({
   logger: rootLogger,
   instrumentationEmitter: rootInstrumentationEmitter,
diff --git a/src/protocol/encoder.js b/src/protocol/encoder.js
index 6275879..5d00245 100644
--- a/src/protocol/encoder.js
+++ b/src/protocol/encoder.js
@@ -280,6 +280,17 @@ module.exports = class Encoder {
     return this
   }
 
+  writeVarUInt(value) {
+    const byteArray = []
+    while ((value & UNSIGNED_INT32_MAX_NUMBER) !== 0) {
+      byteArray.push((value & OTHER_BITS) | MOST_SIGNIFICANT_BIT)
+      value >>>= 7
+    }
+    byteArray.push(value & OTHER_BITS)
+    this.buffer = Buffer.concat([this.buffer, Buffer.from(byteArray)])
+    return this
+  }
+
   writeVarLong(value) {
     const byteArray = []
     let longValue = Encoder.encodeZigZag64(value)
diff --git a/src/protocol/requests/deleteGroups/v2/request.js b/src/protocol/requests/deleteGroups/v2/request.js
index 60a1eea..fbcff07 100644
--- a/src/protocol/requests/deleteGroups/v2/request.js
+++ b/src/protocol/requests/deleteGroups/v2/request.js
@@ -13,7 +13,7 @@ module.exports = groupIds => ({
   apiVersion: 2,
   apiName: 'DeleteGroups',
   encode: async () => {
-    return new Encoder().writeArray(groupIds.map(encodeGroups))
+    return new Encoder().writeArray(groupIds.map(encodeGroups)).writeVarUInt(0)
   },
 })
 
diff --git a/src/protocol/requests/listGroups/v3/request.js b/src/protocol/requests/listGroups/v3/request.js
index 5001f49..895b8ee 100644
--- a/src/protocol/requests/listGroups/v3/request.js
+++ b/src/protocol/requests/listGroups/v3/request.js
@@ -1,7 +1,15 @@
-const requestV2 = require('../v2/request')
+const Encoder = require('../../../encoder')
+const { ListGroups: apiKey } = require('../../apiKeys')
 
 /**
  * ListGroups Request (Version: 3)
  */
 
-module.exports = () => Object.assign(requestV2(), { apiVersion: 3 })
+module.exports = () => ({
+  apiKey,
+  apiVersion: 3,
+  apiName: 'ListGroups',
+  encode: async () => {
+    return new Encoder().writeVarUInt(0)
+  },
+})
```
(rough, don't commit this!)

The problem is that tagged fields are a huge can of worms, and the point of having a Kafka 2.4 docker-compose setup isn't to bring support for all and any 2.4 feature, but just to provide a test bed. So, I'll add a commit here to _remove_ these two requests, and simply use the older versions that do not have a tag buffer.

**Comment by ankon** [comment]
.... and that works and makes Azure happy! :)

**Comment by Nevon** [comment]
Great work figuring that out. Just reading the KIP gave me a headache. 😅 If you fix the conflict in the package.json, we can merge this.

**Comment by ankon** [comment]
Rebased on master for the last time, ready to go :)

**Comment by Nevon** [comment]
> Rebased on master for the last time, ready to go :)

😅 Until I merged your other PR and caused you to have to update your branch again.

**Comment by ankon** [comment]
That's a very nice problem to have :)

**Comment by goriunov** [comment]
FIY kafka 2.4 introduced https://issues.apache.org/jira/browse/KAFKA-9478 this causes quite abit of headache in our production even though this issue is quite rare. 

Symptoms: 

Kafka consume group stop rebalancing so when you try to connect with the same consumer group kafkajs stuck in waiting for JoinGroup request as kafka does not respond anything.


I don't think it affects this PR in any way though 😄

**Pull request merged**
