### PR TITLE
Fix record batch compression masking

### LINKED ISSUE #911: Failing to produce zstandard compressed messages
**Describe the bug**

When producing a message using [https://github.com/kafkajs/zstd](@kafkajs/zstd), the produce is rejected with an `INVALID_RECORD` protocol error.

**To Reproduce**

#910 inspired me to write a zstd codec, which you can find at https://github.com/kafkajs/zstd. Currently its' integration tests are failing.

```sh
$ git clone https://github.com/kafkajs/zstd.git
$ cd zstd
$ npm install
$ docker-compose up -d && node scripts/waitForKafka.js
$ npm test
```

Specifically, see [these tests](https://github.com/kafkajs/zstd/blob/master/src/index.spec.js).

**Expected behavior**

The message should be produced successfully.

**Observed behavior**

On the broker we can see that the record is clearly invalid. It shouldn't matter from Kafka's perspective, but I tried compressing a payload using my compression codec and then decompressing it using native `zstd` and it worked fine, which leads me to believe that both my codec and the underlying compression library are doing the right thing.

```
# When producing without any headers
kafka        | [2020-10-07 11:40:35,005] ERROR [ReplicaManager broker=1] Error processing append operation on partition topic-test-0 (kafka.server.ReplicaManager)
kafka        | org.apache.kafka.common.InvalidRecordException: Found invalid number of record headers -597
kafka        | [2020-10-07 11:40:35,037] ERROR [ReplicaManager broker=1] Error processing append operation on partition topic-test-0 (kafka.server.ReplicaManager)
kafka        | org.apache.kafka.common.InvalidRecordException: Found invalid number of record headers -597

# When producing with headers
kafka        | [2020-10-07 11:40:02,796] ERROR [ReplicaManager broker=1] Error processing append operation on partition topic-test-0 (kafka.server.ReplicaManager)
kafka        | org.apache.kafka.common.InvalidRecordException: Found invalid record structure
kafka        | Caused by: java.lang.IllegalArgumentException
kafka        | 	at java.nio.Buffer.limit(Buffer.java:275)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readHeaders(DefaultRecord.java:545)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:363)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:314)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$3.readNext(DefaultRecordBatch.java:291)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:580)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:549)
kafka        | 	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:44)
kafka        | 	at scala.collection.Iterator$$anon$18.next(Iterator.scala:849)
kafka        | 	at scala.collection.Iterator$$anon$18.next(Iterator.scala:847)
kafka        | 	at scala.collection.Iterator.foreach(Iterator.scala:941)
kafka        | 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
kafka        | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
kafka        | 	at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
kafka        | 	at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
kafka        | 	at scala.collection.IterableViewLike$AbstractTransformed.foreach(IterableViewLike.scala:43)
kafka        | 	at scala.collection.TraversableViewLike$Filtered.foreach(TraversableViewLike.scala:220)
kafka        | 	at scala.collection.TraversableViewLike$Filtered.foreach$(TraversableViewLike.scala:219)
kafka        | 	at scala.collection.IterableViewLike$$anon$8.foreach(IterableViewLike.scala:123)
kafka        | 	at kafka.log.LogValidator$.$anonfun$assignOffsetsNonCompressed$1(LogValidator.scala:280)
kafka        | 	at kafka.log.LogValidator$.$anonfun$assignOffsetsNonCompressed$1$adapted(LogValidator.scala:274)
kafka        | 	at scala.collection.Iterator.foreach(Iterator.scala:941)
kafka        | 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
kafka        | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
kafka        | 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
kafka        | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
kafka        | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
kafka        | 	at kafka.log.LogValidator$.assignOffsetsNonCompressed(LogValidator.scala:274)
kafka        | 	at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:101)
kafka        | 	at kafka.log.Log.liftedTree1$1(Log.scala:1094)
kafka        | 	at kafka.log.Log.$anonfun$append$2(Log.scala:1079)
kafka        | 	at kafka.log.Log.append(Log.scala:2342)
kafka        | 	at kafka.log.Log.appendAsLeader(Log.scala:1022)
kafka        | 	at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:955)
kafka        | 	at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:943)
kafka        | 	at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:809)
kafka        | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
kafka        | 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
kafka        | 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
kafka        | 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
kafka        | 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
kafka        | 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
kafka        | 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
kafka        | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
kafka        | 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
kafka        | 	at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:797)
kafka        | 	at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:521)
kafka        | 	at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:579)
kafka        | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:127)
kafka        | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
kafka        | 	at java.lang.Thread.run(Thread.java:748)
kafka        | [2020-10-07 11:40:02,843] ERROR [ReplicaManager broker=1] Error processing append operation on partition topic-test-0 (kafka.server.ReplicaManager)
kafka        | org.apache.kafka.common.InvalidRecordException: Found invalid record structure
kafka        | Caused by: java.lang.IllegalArgumentException
kafka        | 	at java.nio.Buffer.limit(Buffer.java:275)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readHeaders(DefaultRecord.java:545)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:363)
kafka        | 	at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:314)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$3.readNext(DefaultRecordBatch.java:291)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:580)
kafka        | 	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:549)
kafka        | 	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:44)
kafka        | 	at scala.collection.Iterator$$anon$18.next(Iterator.scala:849)
kafka        | 	at scala.collection.Iterator$$anon$18.next(Iterator.scala:847)
kafka        | 	at scala.collection.Iterator.foreach(Iterator.scala:941)
kafka        | 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
kafka        | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
kafka        | 	at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
kafka        | 	at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
kafka        | 	at scala.collection.IterableViewLike$AbstractTransformed.foreach(IterableViewLike.scala:43)
kafka        | 	at scala.collection.TraversableViewLike$Filtered.foreach(TraversableViewLike.scala:220)
kafka        | 	at scala.collection.TraversableViewLike$Filtered.foreach$(TraversableViewLike.scala:219)
kafka        | 	at scala.collection.IterableViewLike$$anon$8.foreach(IterableViewLike.scala:123)
kafka        | 	at kafka.log.LogValidator$.$anonfun$assignOffsetsNonCompressed$1(LogValidator.scala:280)
kafka        | 	at kafka.log.LogValidator$.$anonfun$assignOffsetsNonCompressed$1$adapted(LogValidator.scala:274)
kafka        | 	at scala.collection.Iterator.foreach(Iterator.scala:941)
kafka        | 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
kafka        | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
kafka        | 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
kafka        | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
kafka        | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
kafka        | 	at kafka.log.LogValidator$.assignOffsetsNonCompressed(LogValidator.scala:274)
kafka        | 	at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:101)
kafka        | 	at kafka.log.Log.liftedTree1$1(Log.scala:1094)
kafka        | 	at kafka.log.Log.$anonfun$append$2(Log.scala:1079)
kafka        | 	at kafka.log.Log.append(Log.scala:2342)
kafka        | 	at kafka.log.Log.appendAsLeader(Log.scala:1022)
kafka        | 	at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:955)
kafka        | 	at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:943)
kafka        | 	at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:809)
kafka        | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
kafka        | 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
kafka        | 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
kafka        | 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
kafka        | 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
kafka        | 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
kafka        | 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
kafka        | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
kafka        | 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
kafka        | 	at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:797)
kafka        | 	at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:521)
kafka        | 	at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:579)
kafka        | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:127)
kafka        | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
kafka        | 	at java.lang.Thread.run(Thread.java:748)
```

**Environment:**
 - OS: Mac OS 10.15.6
 - KafkaJS version: 1.14.0
 - Kafka version: 2.4.0
 - NodeJS version: 14.5.0

### PR DESCRIPTION
**Pull request by Nevon**
Debugging this almost killed me...

Fixes #911

We were accidentally using the wrong masking value for getting the compression codec out of the recordbatch attributes (3 instead of 7). This worked for other compression types than zstd, but failed for zstd.

The reason is because to get the last 3 bytes, we need to AND it with 7 (`111`), not 3 (`010`). But for certain values, it will work anyway. Using Snappy as an example. Snappy = 2 (010 in binary). The compression masking value for the Message type is 3 (011 in binary). 2 & 3 = 2.

```
010
011
===
010
```

The correct masking value = 7. 2 & 7 = 2.

```
010
111
===
010
```

Now Zstd is 4 (100 in binary). 4 & 3 = 0.

```
100
011
===
000
```

The correct masking value = 7. 4 & 7 = 4.

```
100
111
===
000
```

For the old Message type, the attribute value is int8, rather than int16, which is why the correct value is 3 (`011`), since we want to get the last two bits - not three.

### CODE REVIEW

**Comment by ankon** [comment]
First of all, nice find!

> For the old Message type, the attribute value is int8, rather than int16, which is why the correct value is 3 (011), since we want to get the last two bits - not three.

I found this curious, so wanted to check. Looking at http://kafka.apache.org/documentation/#messageset it still specifies the last _3_ bits for the compression (`bit 0~2`, where the count starts at 0). This is identical for the new "RecordBatch" (http://kafka.apache.org/documentation/#recordbatch), where just more attributes got added at the end.

Am I missing something?

**Comment by Nevon** [comment]
> Am I missing something?

I originally thought that we wanted the three last bits also for the legacy message type (which is why I updated it in d32ff09, but once I saw failing tests with INVALID_RECORD errors I figured I was mistaken and reverted. But indeed, you are correct, the specification does say that it should be the same also for the older version.

In practice, it won't really make a difference since only compression codecs 1-3 are available with the old message type, all of which fit into 2 bits, but now I want to understand why it doesn't work when I change it. Will investigate further.

**Comment by Nevon** [comment]
I must have made some mistake last night when things were failing after fixing the codec mask for message set. I tried it again now, and it worked just fine. I even ran the produce tests with 0_11, and while the tests failed due to the expectations being written for newer protocol versions, the actual producing worked.

**Review by tulios — APPROVED** [review]

**Comment by tulios** [comment]
4ht8z5

**Pull request merged**
