### PR TITLE
feat: add consumer.paused() to get the list of paused topics

### LINKED ISSUE #415: Add a paused method to consumer
ATM the consumer doesn't expose the `paused()` method from `consumerGroup`. It looks trivial to do so, so...any reason I am missing not to?
Happy to submit a PR for it if you're ok with a `consumer.paused()` method.

### PR DESCRIPTION
**Pull request by terebentina**
Closes #415

### CODE REVIEW

**Comment by JaapRood** [comment]
Just as you added this we've been working on #417, which changes the internals that this exposes. A small layer is probably required to make that ready for public consumption, to resolve the partitions that _should_ be paused through `SubscriptionState` and apply them to the current member assignment of `consumerGroup`, rendering which partitions _are_ actually paused.

**Comment by terebentina** [comment]
Heh, this is why I asked about non-obvious reasons why this method hasn't been exposed already. Just make sure you do expose a `consumer.paused()` method in your PR and I am good, I can work with it.

**Comment by JaapRood** [comment]
I've started work on changing the internals through #429. Once that's merged, this should work as designed, returning all `TopicPartition`s that are currently assigned and paused.

**Comment by tulios** [comment]
@terebentina after #429 is merged I can expose the paused method.

**Comment by tulios** [comment]
I moved the changes to PR #444

**Pull request closed without merging**
