### PR TITLE
Add error.js to typescript types

### PR DESCRIPTION
**Pull request by uc4w6c**
add #616 
Nice to meet you

This is to export error classes from error.js

### CODE REVIEW

**Comment by uc4w6c** [comment]
I don't know why it fails

**Comment by tulios** [comment]
@uc4w6c I will take a look, it might just be a flaky test. I can re-run the group that is failing. Should I re-open the PR?

**Comment by uc4w6c** [comment]
@tulios 
Really?
Thank you by all means.

**Comment by Nevon** [comment]
Sorry that it took some time to get to this.

**Comment by uc4w6c** [comment]
@Nevon 
I'm happy!!
Special thanks!

**Pull request merged**
