### PR TITLE
Refresh metadata on connection error [#950]

### PR DESCRIPTION
**Pull request by smartinio**
As I'm relatively new to the KafkaJS codebase, I might be missing some context as to why the code I'm submitting isn't already the case.

See #950

### CODE REVIEW

**Comment by tulios** [comment]
@smartinio this is covered in a layer above:
https://github.com/tulios/kafkajs/blob/daeec895c09828622a550134b7cf9b1c0ceebded/src/producer/messageProducer.js#L117-L127

but you haven't seen the message `Failed to send messages: ...`, which means the client is first doing network retries. I think it will eventually retry the messages once the error bubbles up.

**Comment by tulios** [comment]
The client should also distinguish between a regular network error and a broker going offline, so the messages you are seeing are due to network issues while the broker is going down but is not yet fully down.

https://github.com/tulios/kafkajs/blob/daeec895c09828622a550134b7cf9b1c0ceebded/src/network/connection.js#L137-L143

Once the broker is offline, the client will propagate the error and fully refresh the metadata.

In the issue you mentioned that you are using version `1.12.0`, I recommend you to use the latest pre-release or at least the latest version first.

**Comment by smartinio** [comment]
> but you haven't seen the message `Failed to send messages: ...`, which means the client is first doing network retries. I think it will eventually retry the messages once the error bubbles up.

@tulios Yeah I don't have "Failed to send messages" anywhere in my service logs. Since I'm seeing "Connection timeout", could it be related to this deadlock issue that was recently fixed, but only fixed in the `onError` handler?
> https://github.com/tulios/kafkajs/blob/3bd245d31f10acf83c91cba00e8cbb983947add5/src/network/connection.js#L164-L173

**Comment by smartinio** [comment]
Closing this in favor of #956.

**Pull request closed without merging**
