### PR TITLE
fix(test): fixed username shadowing in test scram setup

### PR DESCRIPTION
**Pull request by galesky**
## Issue
https://github.com/tulios/kafkajs/issues/703

In addition to fixing the related issue, I've also included user feedback in the execution which can help to detect bugs such as this one.

### CODE REVIEW

**Comment by Nevon** [comment]
Thanks for looking into the issue. How about instead of relying on environment variables, we move to taking the username and password as parameters that are passed in when you execute the script? `./createScramCredentials foo bar`

We can still have default values, same as now, but not using environment variables would remove the risk of someone running into the same issues as you are now.

**Comment by galesky** [comment]
That's a good idea, kinda moves in a way so it can be implemented as part of a CLI in the future.

I'll take a look at updating `./createScramCredentials` later today;

**Comment by galesky** [comment]
Hi @Nevon , I've added some flags, basic docs and behaviors; 

Just want to check with you if that aligned to what you were expecting if so I'll also update the docs at least to indicate that those new commands are available
 
output

**Comment by Nevon** [comment]
That's quite a bit more advanced than what I had in mind, but sure, it seems to work great.

**Comment by galesky** [comment]
Yeah, I tried to stay as lean as possible so as to handle only the `username` and `password` but while also doing some checks and falling back to default values. 

I've updated the docs now to reference the new controls and it seems ready to me.

**Pull request merged**
