### PR TITLE
add error names to ensure error names work with webpack + uglify

### PR DESCRIPTION
**Pull request by ledbit**
Set name for errors to allow for the field to be used in mangled code. Addresses #600

### CODE REVIEW

**Comment by tulios** [comment]
Hi @ledbit, I will discuss this change with the team. Where are you using KafkaJS with webpack + uglifier? Because, you might find other challenges.

**Comment by ledbit** [comment]
We're bundling it as part of our single file, NodeJS (10.x) application. What kind of other issues/challenges are you thinking we'd run into?

**Comment by Nevon** [comment]
I think he was wondering if you were trying to run it in a non-Node environment (such as browsers, which won't work out of the box), since it's somewhat unusual to do bundling and minification in Node.

**Comment by Nevon** [comment]
Thanks for the contribution! This will be available in 1.12.0-beta.14 as soon as [this build](https://dev.azure.com/tulios/kafkajs/_build/results?buildId=603&view=results) is done.

**Pull request merged**
